services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
    - "${POSTGRESS_PORT}:${POSTGRESS_PORT}"
    volumes:
    - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    ports:
    - "8000:8000"
    volumes:
    - ".:/app:z"
    depends_on:
    - db
    env_file:
    - .env

  n8n:
    image: n8nio/n8n
    ports:
    - "${N8N_PORT}:${N8N_PORT}"
    depends_on:
    - api
    - db
    volumes:
    - n8n_data:/home/node/.n8n
    env_file:
      - .env
  
  frontend:
    build: ./frontend
    ports:
    - "3000:3000"
    - "8001:8001"
    volumes:
    - ./frontend:/app:z

volumes:
  postgres_data:
  n8n_data:
  frontend: